"""add columns to account

Revision ID: b478214b45c9
Revises: 89f7ec6e8441
Create Date: 2023-10-12 21:12:15.808724

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b478214b45c9"
down_revision: Union[str, None] = "89f7ec6e8441"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("disabled", sa.Boolean(), nullable=False))
    op.add_column(
        "account",
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(length=72), nullable=True),
    )
    op.add_column("account", sa.Column("external_oauth", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###

    op.create_check_constraint(
        "hashed_password_is_nullable_when_external_oauth_is_true",
        "account",
        "(hashed_password IS NULL AND external_oauth = TRUE) OR (hashed_password IS NOT NULL AND external_oauth = FALSE)",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("account", "external_oauth")
    op.drop_column("account", "hashed_password")
    op.drop_column("account", "disabled")
    # ### end Alembic commands ###
