repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      # - id: no-commit-to-branch
      #   args: ['--branch', 'main']

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.48.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@^8.48.0
          - eslint-config-airbnb@^19.0.4
          - eslint-config-prettier@^9.0.0
          - eslint-config-react-app@^7.0.1
          - eslint-plugin-import@^2.28.1
          - eslint-plugin-jsx@^0.1.0
          - eslint-plugin-prettier@^5.0.0
          - eslint-plugin-react@^7.33.2
          - eslint-plugin-react-hooks@^4.6.0

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  # - repo: https://github.com/antonbabenko/pre-commit-terraform
  #   rev: v1.83.0
  #   hooks:
  #     - id: terraform_fmt
  #     - id: terraform_docs

  - repo: https://github.com/iamthefij/docker-pre-commit
    rev: v3.0.1
    hooks:
      - id: docker-compose-check

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
