version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi-app
    volumes:
      - ./api:/app
      - db-data:/var/lib/postgresql/data
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql+asyncpg://postgres_user:placeholder_password@db:5432/postgres_db
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=placeholder_password
      - POSTGRES_DB=postgres_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data:
