version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      env_file: .env.development
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    networks:
      - fastapi-network
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi-app
    volumes:
      - ./api:/app
      - db-data:/var/lib/postgresql/data
    environment:
      - ENV=dev
      - DB_URL=postgresql+asyncpg://myuser:mypassword@db:5432/mydb
    ports:
      - 8080:8080
    networks:
      - fastapi-network
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - fastapi-network

  test_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=test-db
    ports:
      - 5433:5432
    networks:
      - fastapi-network

volumes:
  db-data:

networks:
  fastapi-network:
